### ISSUE TITLE
doing blackbox testing

### ISSUE THREAD

**Issue by namluu25** [namluu25/NMM-Techstore#41]
checklist for us to test, using cypress

- [x] header button a.k.a nav bar

- [x] signin/signout

- [x] registration

- [x] dropdown menu

- [x] scroll 

- [x] product view

**Comment by namluu25** [comment]
@trinhtuanminh2000 can you do the register? i'll do the dropdown

**Comment by trinhtuanminh2000** [comment]
sure with pleasure

**Comment by namluu25** [comment]
finished #41
